
### resend hawa code

PUT http://localhost:8080/api/v1/utilisateurs/resendCode
Content-Type: application/json

{
  "email": "diallo.habibatou2710@gmail.com"
}


### enbale accout of user

PUT http://localhost:8080/api/v1/utilisateurs/enableAccount
Content-Type: application/json

{
  "code": "619547"
}