
### resend hawa code

PUT http://localhost:8080/api/v1/utilisateurs/resendCode
Content-Type: application/json

{
  "email": "ndey.sira@gmail.com"
}


### enbale accout of user

PUT http://localhost:8080/api/v1/utilisateurs/enableAccount
Content-Type: application/json

{
  "code": "391520"
}