### authentication 0

POST http://localhost:8080/api/v1/authenticate
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "Alphadjo30901@"
}

### authentication 1

POST http://localhost:8080/api/v1/authenticate
Content-Type: application/json

{
  "email": "alphadiobiya@gmail.com",
  "password": "Alphadjo30901@"
}

### authentication 2

POST http://localhost:8080/api/v1/authenticate
Content-Type: application/json

{
  "email": "diallo.habibatou2710@gmail.com",
  "password": "Alphadjo30901@"
}

### inscription alphadjo

POST http://localhost:8080/api/v1/utilisateurs/user
Content-Type: application/json

{
  "firstName": "Alphadjo",
  "lastName": "barry",
  "password": "Alphadjo30901@",
  "email": "alphadiobiya@gmail.com",
  "phone": "+33661474742"
}

### inscription Habibatou

POST http://localhost:8080/api/v1/utilisateurs/user
Content-Type: application/json

{
  "firstName": "Habibatou",
  "lastName": "Diallo",
  "password": "Alphadjo30901@",
  "email": "diallo.habibatou2710@gmail.com",
  "phone": "+33651598978"
}

### enbale accout of user

PUT http://localhost:8080/api/v1/utilisateurs/enableAccount
Content-Type: application/json

{
  "code": "288038"
}